Add placeholder
The placeholder is mentioned in the kafkaConsumer.java but didn't defined in the applications.prop. So we need to defined that.

Current exception is as follow.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaConsumer' defined in file [/Users/mac/Library/Mobile Documents/com~apple~CloudDocs/development/kafka-poc/producer/target/classes/com/ef/kafka/embedded/KafkaConsumer.class]: Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'test.topic' in value "${test.topic}"

Former-commit-id: 8d58453a021706095cebc873d58c20d257d30408